config/routes.rb
Rails.application.routes.draw do
  get 'videos/index'
  root 'top_pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :web_apps
  resources :articles
  resources :articles, only: [:index] do
    collection do
      post :import
    end
  end
  resources :videos
  resources :videos, only: [:index] do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :web_apps, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  devise :omniauthable, omniauth_providers: %i[github]
  validates :uid, uniqueness: { scope: :provider }, if: -> { uid.present? }

  def self.from_omniauth(auth)
    where(uid: auth.uid, provider: auth.provider).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/models/video.rb
class Video < ApplicationRecord
end

app/models/web_app.rb
class WebApp < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 65_535 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :github_url, length: { maximum: 255 }

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true).page(params[:page]).per(12)
  end

  def new
  end

  def import
    ArticleImporter.new(ENV['QIITA_API_TOKEN']).import('Rails')
    redirect_to articles_path, notice: 'Articles imported successfully.'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  def home
    @videos = Video.order(publish_datetime: :desc).limit(3)
    @web_apps = WebApp.order(created_at: :desc).limit(3)
    @articles = Article.order(post_datetime: :desc).limit(3)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :github
  
  def github
    # ユーザー情報を取得
    @user = User.from_omniauth(request.env['omniauth.auth'])

    # ユーザーを検索または作成
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["divise.github_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end
  

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def import
    importer = YoutubeVideoImporter.new(ENV['YOUTUBE_API_KEY'])
    importer.import('Ruby on Rails プログラミング エンジニア')
    flash[:success] = "動画をインポートしました"
    redirect_to videos_path
  end

  def index
    @q = Video.ransack(params[:q])
    @videos = @q.result(distinct: true).page(params[:page]).per(12)
  end

end

app/controllers/web_apps_controller.rb
class WebAppsController < ApplicationController
  def index
    @q = WebApp.ransack(params[:q])
    @web_apps = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(12)
  end

  def show
    @web_app = WebApp.find_by(id: params[:id])
  end

  def new
    @web_app = WebApp.new
  end

  def create
    @web_app = WebApp.new(web_app_params)
    if @web_app.save
      flash[:success] = "アプリを投稿しました"
      redirect_to web_apps_path
    else
      flash[:danger] = "アプリの投稿に失敗しました"
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @web_app = current_user.web_apps.find(params[:id])
  end

  def update
    @web_app = current_user.web_apps.find(params[:id])
    if @web_app.update(web_app_params)
      flash[:success] = "投稿アプリを編集しました"
      redirect_to web_app_path(@web_app)
    else
      flash[:danger] = "投稿アプリの編集に失敗しました"
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    web_app = WebApp.find(params[:id])
    web_app.destroy
    flash[:success] = "投稿アプリを削除しました"
    redirect_to web_apps_path
  end

  def web_app_params
    params.require(:web_app).permit(:title, :description, :image, :url, :github_url, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/web_apps_helper.rb
module WebAppsHelper
end

app/views/articles/index.html.erb
<div class="container pt-3 mb-5">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 text-center">
      <%= render 'shared/articles_search_form', q: @q, url: articles_path %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @articles.count != 0 %>
          <div class="col-12 d-flex justify-content-center mb-3">
            <%= paginate @articles %>
          </div>
          <% @articles.each do |article| %>
            <div class="col-sm-12 col-lg-3 mb-3">
              <div id="article-id-<%= article.id %>">
                <div class="card">
                  <%= image_tag 'qiita.webp', class: 'card-img-top', size: "120x120" %>
                  <div class="card-body d-flex flex-column">
                    <p class="card-title mb-2">
                      <%= link_to truncate(article.title, length: 64), article.url %>
                    </p>
                    <div class="mt-auto">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          <div class="col-12 d-flex justify-content-center">
            <%= paginate @articles %>
          </div>
        <% else %>
          <div class="col-12">
            <p>投稿はありません</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= button_to 'Import Articles', import_articles_path, method: :post, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_articles_search_form.erb
<%= search_form_for q, url: url do |f| %>
  <div class="input-group mb-3">
    <%= f.search_field :title_cont, class: "form-control", placeholder: "技術記事をキーワードで検索できます" %>
    <div class="input-group-append">
      <%= f.submit "検索", class: "btn btn-primary ms-2" %>
    </div>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">

      <div class="d-flex">
        <div class="text-light">
          <%= link_to "Railsるーむ", root_path, class: "navbar-brand fs-6" %>
        </div>
      </div>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">
          <% if user_signed_in? %>
            <%= link_to "アプリを投稿する", new_web_app_path, class: "nav-link text-white" %>
            <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link text-white" %>
          <% else %>
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-white" %>
            <%= link_to "ログイン", new_user_session_path, class: "nav-link text-white" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>

  <nav class="navbar navbar-expand-md navbar-dark bg-danger py-0">
    <div class="container-fluid">
      <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "個人開発アプリ", web_apps_path, class: "nav-link text-white mx-2" %>
          <%= link_to "技術記事", articles_path, class: "nav-link text-white mx-2" %>
          <%= link_to "動画コンテンツ", videos_path, class: "nav-link text-white mx-2" %>
          <%= link_to "Railsを学びたい方", "#", class: "nav-link text-white mx-2" %>
          <%= link_to "Railsを採用している企業", "#", class: "nav-link text-white mx-2" %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_search_form.erb
<%= search_form_for q, url: url do |f| %>
  <div class="input-group mb-3">
    <%= f.search_field :title_or_description_cont, class: "form-control", placeholder: "アプリの件名や概要をキーワードで検索できます" %>
    <div class="input-group-append">
      <%= f.submit "検索", class: "btn btn-primary ms-2" %>
    </div>
  </div>
<% end %>

app/views/shared/_videos_search_form.erb
<%= search_form_for q, url: url do |f| %>
  <div class="input-group my-5">
    <%= f.search_field :title_cont, class: "form-control", placeholder: "動画コンテンツをキーワードで検索できます" %>
    <div class="input-group-append">
      <%= f.submit "検索", class: "btn btn-primary ms-2" %>
    </div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

<button type="button" class="btn btn-primary">Bootstrap Test</button>

app/views/top_pages/home.html.erb
<div class="text-center my-5 py-3">
  <h3>Railsアプリを投稿したり、Rails好き同士で繋がれる</h3>
  <h3>Railsユーザーのためのアプリ兼ファンサイトです</h3>
</div>

<div class="text-center my-5 py-3">
  <h5>Railsで開発されたアプリを投稿、検索、お気に入り登録できる</h5>
  <h5>Railsに関する技術記事や動画コンテンツを検索、お気に入り登録できる</h5>
  <h5>マイページを充実させて、他のRailsユーザーと繋がれる</h5>
</div>

<div class="container pt-3">
  <div class="row">
    <div class="col-sm-12 col-md-4 mb-3">
      <h3 class="text-center mb-5">最新投稿動画</h3>
      <% if @videos.any? %>
        <% @videos.first(3).each do |video| %>
          <div class="card mb-3" style="height: 280px;">
            <%= image_tag video.thumbnail_url, class: 'card-img-top', style: 'height: 120px; object-fit: cover;' %>
            <div class="card-body d-flex flex-column">
              <p class="card-title mb-2">
                <%= link_to truncate(video.title, length: 64), video.url %>
              </p>
              <div class="mt-auto">
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>動画はありません</p>
      <% end %>
    </div>

    <div class="col-sm-12 col-md-4 mb-3">
      <h3 class="text-center mb-5">最新投稿アプリ</h3>
      <% if @web_apps.any? %>
        <% @web_apps.first(3).each do |web_app| %>
          <div class="card mb-3" style="height: 280px;">
            <% if web_app.image? %>
              <%= image_tag web_app.image.url, class: 'card-img-top', style: 'height: 120px; object-fit: cover;' %>
            <% else %>
              <%= image_tag '320x240.png', class: 'card-img-top', style: 'height: 120px; object-fit: cover;' %>
            <% end %>
            <div class="card-body d-flex flex-column">
              <p class="card-title mb-2">
                <%= link_to truncate(web_app.title, length: 64), web_app_path(web_app) %>
              </p>
              <div class="mt-auto">
                <p><%= truncate(web_app.description, length: 64) %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>投稿アプリはありません</p>
      <% end %>
    </div>

    <div class="col-sm-12 col-md-4 mb-3">
      <h3 class="text-center mb-5">最新投稿記事</h3>
      <% if @articles.any? %>
        <% @articles.first(3).each do |article| %>
          <div class="card mb-3" style="height: 280px;">
            <%= image_tag 'qiita.webp', class: 'card-img-top', style: 'height: 120px; object-fit: cover;' %>
            <div class="card-body d-flex flex-column">
              <p class="card-title mb-2">
                <%= link_to truncate(article.title, length: 64), article.url %>
              </p>
              <div class="mt-auto">
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>記事はありません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<div class="container pt-3 mb-5">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 text-center">
      <%= render 'shared/articles_search_form', q: @q, url: videos_path %>
    </div>
  </div>
  <div class="row">
    <% if @videos.count != 0 %>
      <div class="col-12 d-flex justify-content-center mb-3">
        <%= paginate @videos %>
      </div>
      <% @videos.each do |video| %>
        <div class="col-sm-12 col-lg-3 mb-3">
          <div id="video-id-<%= video.id %>">
            <div class="card">
                <%= image_tag video.thumbnail_url, class: 'card-img-top', size: "120x180" %>
              <div class="card-body">
                <p class="card-title">
                  <%= link_to truncate(video.title, length: 64), video.url, target: "_blank" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="col-12 d-flex justify-content-center">
        <%= paginate @videos %>
      </div>
    <% else %>
      <div class="col-12">
        <p>投稿はありません</p>
      </div>
    <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<%= button_to 'Import Videos', import_videos_path, method: :post, class: 'btn btn-primary' %>

app/views/web_apps/_web_app.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="web_app-id-<%= web_app.id %>">
    <div class="card">
      <% if web_app.image? %>
        <%= image_tag web_app.image.url, class: 'card-img-top' %>
      <% else %>
        <%= image_tag '320x240.png', class: 'card-img-top' %>
      <% end %>
      <div class="card-body">
        <div class="d-flex">
          <h4 class="card-title">
            <%= link_to web_app.title, web_app_path(web_app) %>
          </h4>
        </div>
        <p class="card-text"><%= web_app.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/web_apps/create.html.erb
<h1>WebApps#create</h1>
<p>Find me in app/views/web_apps/create.html.erb</p>

app/views/web_apps/destroy.html.erb
<h1>WebApps#destroy</h1>
<p>Find me in app/views/web_apps/destroy.html.erb</p>

app/views/web_apps/edit.html.erb
<% if @web_app.errors.any? %>
	<div class="alert alert-danger">
    <ul>
      <% @web_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h1>アプリ編集画面</h1>
<div class="container py-5">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <%= form_with model: @web_app do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="mb-3">
          <%= f.label "タイトル" %>
          <%= f.text_field :title, class: 'form-control', id: 'web_app_title' %>
        </div>
        <div class="mb-3">
          <%= f.label "概要" %>
          <%= f.text_area :description, class: 'form-control', id: 'web_app_description' %>
        </div>
        <div class="mb-3">
          <%= f.label "サムネイル" %>
          <%= f.file_field :image, class: 'form-control', id: 'web_app_image' %>
          <div class="text-center py-2"> 
            <%= image_tag @web_app.image_url, class: 'w-75', style: "width: 640px; height: 320px;" if @web_app.image? %>
          </div>
          <%= f.hidden_field :web_app_image_cache %>
        </div>
        <div class="mb-3">
          <%= f.label "URL" %>
          <%= f.text_field :url, class: 'form-control', id: 'web_app_url' %>
        </div>
        <div class="mb-3">
          <%= f.label "GitHub URL" %>
          <%= f.text_field :github_url, class: 'form-control', id: 'web_app_github_url' %>
        </div>
        <%= f.submit "更新", class: 'btn btn-primary', data: { disable_with: "更新" } %>
        <%= link_to "削除", web_app_path(@web_app), data: { turbo_method: :delete }, class: 'btn btn-danger' %>
      <% end %>
    </div>
  </div>
</div>

app/views/web_apps/index.html.erb
<div class="container pt-3 mb-5">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 text-center my-5">
      <%= link_to "アプリを投稿する", new_web_app_path, class: "btn btn-primary mb-5" %>
      <%= render 'shared/search_form', q: @q, url: web_apps_path %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @web_apps.count != 0 %>
          <div class="col-12 d-flex justify-content-center mb-3">
            <%= paginate @web_apps %>
          </div>
          <% @web_apps.each do |web_app| %>
            <div class="col-sm-12 col-lg-4 mb-3">
              <div id="web_app-id-<%= web_app.id %>">
                <div class="card">
                  <% if web_app.image? %>
                    <%= image_tag web_app.image.url, class: 'card-img-top', size: "300x250" %>
                  <% else %>
                    <%= image_tag '320x240.png', class: 'card-img-top', size: "300x250" %>
                  <% end %>
                  <div class="card-body">
                    <div class="d-flex">
                      <h4 class="card-title">
                        <%= link_to web_app.title, web_app_path(web_app) %>
                      </h4>
                    </div>
                    <p class="card-text"><%= web_app.description %></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          <div class="col-12 d-flex justify-content-center">
            <%= paginate @web_apps %>
          </div>
        <% else %>
          <div class="col-12">
            <p>投稿はありません</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/web_apps/new.html.erb
<% if @web_app.errors.any? %>
	<div class="alert alert-danger">
    <ul>
      <% @web_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h1>アプリ投稿画面</h1>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <%= form_with model: @web_app do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="mb-3">
          <%= f.label "タイトル" %>
          <%= f.text_field :title, class: 'form-control', id: 'web_app_title' %>
        </div>
        <div class="mb-3">
          <%= f.label "概要" %>
          <%= f.text_area :description, class: 'form-control', id: 'web_app_description' %>
        </div>
        <div class="mb-3">
          <%= f.label "サムネイル" %>
          <%= f.file_field :image, class: 'form-control', id: 'web_app_image' %>
        </div>
        <div class="mb-3">
          <%= f.label "URL" %>
          <%= f.text_field :url, class: 'form-control', id: 'web_app_url' %>
        </div>
        <div class="mb-3">
          <%= f.label "GitHub URL" %>
          <%= f.text_field :github_url, class: 'form-control', id: 'web_app_github_url' %>
        </div>

        <%= f.submit "投稿する", class: 'btn btn-primary', data: { disable_with: "投稿する" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/web_apps/show.html.erb
<h1>アプリ詳細画面</h1>

<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-7 offset-lg-3">
      <article class="card">
        <div class="card-body">
          <h2 class="border-bottom pb-3"><%= @web_app.title %></h2>
          <div class="pb-3 text-center">
            <% if @web_app.image? %>
              <%= image_tag @web_app.image.url, class: 'card-img-top img-fluid', style: "width: 640px; height: 400px;" %>
            <% else %>
              <%= image_tag '320x240.png', class: 'card-img-top', style: "width: 640px; height: 400px;" %>
            <% end %>
          </div>
          <h5>概要</h5>
          <p><%= @web_app.description %></p>
          <p>URL: <%= link_to @web_app.url %></p>
          <p>GitHub: <%= link_to @web_app.github_url %></p>
          <div class='d-flex justify-content-end'>
            <% if @web_app.user == current_user %>
              <%= link_to edit_web_app_path(@web_app), class: "btn btn-primary me-2", id: "button-edit-#{@web_app.id}" do %>
                <i class='bi bi-pencil-fill'></i> 編集
              <% end %>
            <% end %>
              </div>
            </div>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/web_apps/update.html.erb
<h1>WebApps#update</h1>
<p>Find me in app/views/web_apps/update.html.erb</p>